name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        example: [.]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - name: Install PlatformIO
        run: |
          pip install -U pip setuptools wheel
          pip install platformio 
      - name: Install LSM9DS1 Library
        run: pio lib -g install arduino-libraries/Arduino_LSM9DS1
      - name: Install LPS22HB Library
        run: pio lib -g install arduino-libraries/Arduino_LPS22HB
      - name: Run PlatformIO
        run: |
          pio ci --lib="." --board=nano33ble
        env:
          PLATFORMIO_CI_SRC: ${{ matrix.example }}
